# Generated by Django 4.2.1 on 2023-07-11 13:25
from django.contrib.auth import get_user_model
from django.contrib.auth.hashers import make_password
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def populate_user(apps, schema_editor):
    User = get_user_model()
    SU_Staff = apps.get_model('su_staffs', 'SU_Staff')

    # Retrieve all SU_Staff objects
    su_staffs = SU_Staff.objects.all()

    for su_staff in su_staffs:
        # Generate the username and password
        username = su_staff.staff_id
        password = 'init' + su_staff.staff_id


        # Create a new User object
        user = User(
            username=username,
            password=make_password(password),
        )

        # Save the User object
        user.save()

        try:
            su_staff.user = user
            su_staff.save()
        except Exception as e:
            print(f"Error Occured {e}")

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('su_staffs', '0018_remove_su_staff_user'),
    ]

    operations = [
        migrations.RunPython(populate_user),
        migrations.AddField(
            model_name='su_staff',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
